CREATE TABLE IF NOT EXISTS Staff (
    StaffID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    StartingDate DATE NOT NULL,
    Position ENUM('Manager', 'Staff') NOT NULL,
    Salary FLOAT8 NOT NULL,
    Purchases INT,
    Logins INT,
    SessionsWeek INT,
    SessionsMonth INT,
    SessionsTotal INT
);

CREATE TABLE IF NOT EXISTS Customer (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Phone BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Finances (
    FinanceID INT AUTO_INCREMENT PRIMARY KEY,
    Date VARCHAR(255) NOT NULL,
    Revenue FLOAT8 NOT NULL,
    Profit FLOAT8 NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
    BookID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    ReleaseDate DATE NOT NULL,
    Genre VARCHAR(255) NOT NULL,
    Language VARCHAR(255) NOT NULL,
    Price FLOAT8 NOT NULL,
    Pages INT NOT NULL,
    Stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS DVD (
    DvdID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    ReleaseDate DATE NOT NULL,
    Genre VARCHAR(255) NOT NULL,
    Language VARCHAR(255) NOT NULL,
    Price FLOAT8 NOT NULL,
    Length INT NOT NULL,
    Stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS CD (
   DvdID INT AUTO_INCREMENT PRIMARY KEY,
   Title VARCHAR(255) NOT NULL,
   Author VARCHAR(255) NOT NULL,
   ReleaseDate DATE NOT NULL,
   Genre VARCHAR(255) NOT NULL,
   Language VARCHAR(255) NOT NULL,
   Price FLOAT8 NOT NULL,
   Tracks NVARCHAR(255) NOT NULL,
   Stock INT NOT NULL
);
