/*
 * This source file was generated by the Gradle 'init' task
 */
package app;
import app.controller.sql.DBInitialize;
import app.controller.sql.DBInterface;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        try {
            DBInitialize db = new DBInitialize();
            db.initializeDatabase();
            System.out.println(DBInterface.pullTable("customer"));
        }
        catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }
}
