/*
 * This source file was generated by the Gradle 'init' task
 */
package app;
import db.*;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        DBInitialize db = new DBInitialize();
        db.initializeDatabase();
    }
}
